name: Deploy dashrando.github.io to GitHub Pages

on:
  push:
    branches: ["main", "github-pages-redirect"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build Minified script file for CLI
        run: |
          cd apps/github-pages-redirect
          npm install
          npm run build
      - name: Build redirect pages
        run: |
          npm run redirects
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './apps/github-pages-redirect/public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
